# Generated by Django 4.1.7 on 2023-03-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='post',
            new_name='news',
        ),
    ]
