# Generated by Django 4.1.7 on 2023-03-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_rename_post_postcategory_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='News',
            new_name='News',
        ),
    ]
