# Generated by Django 4.1.7 on 2023-03-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_rename_news_postcategory_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='News',
            new_name='news',
        ),
    ]
