# Generated by Django 4.1.7 on 2023-04-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='news', through='News.PostCategory', to='News.category'),
        ),
    ]
